apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

images:
  - name: k8s.gcr.io/external-dns/external-dns
    newTag: v0.10.1

# https://raw.githubusercontent.com/kubernetes-sigs/external-dns/v0.10.1/docs/contributing/crd-source/crd-manifest.yaml
resources:
  - ./crd-manifest.yaml
  - ./namespace.yaml
  - ./manifests.yaml

